stages:
  - linters
  - tests
  - e2e
  - final


flake8:
  stage: linters
  image: python:3.12
  allow_failure: true

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install flake8

  script:
    - |
      echo "Запуск flake8"
      set +e
      flake8 . > flake8-report.txt
      status=$?
      cat flake8-report.txt
      exit $status

  artifacts:
    when: always
    paths:
      - flake8-report.txt
    expire_in: 7 days


pylint:
  stage: linters
  image: python:3.12
  allow_failure: true

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install pylint

  script:
    - echo "Запуск pylint"
    - pylint .


ruff:
  stage: linters
  image: python:3.12
  allow_failure: true

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install ruff

  script:
    - echo "Запуск ruff"
    - ruff check .


tests:
  stage: tests
  image: python:3.12

  rules:
    - when: always

  before_script:
    - echo "Установка пакетов"
    - apt-get update -y
    - apt-get install -y --no-install-recommends default-jre-headless nodejs npm
    - npm install -g allure --unsafe-perm=true

    - echo "Установка зависимостей"
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - |
      set +e

      echo "Запуск API-тестов"
      pytest -m api

      status=$?
      echo "Pytest exit code: $status"

      echo "Генерация отчёта"
      allure awesome allure-results \
        --single-file \
        --output allure-report

      exit $status

  artifacts:
    when: always
    paths:
      - allure-results/
      - allure-report/
    expire_in: 7 days


e2e_tests:
  stage: e2e
  rules:
    - when: always

  trigger:
    project: python-auto-qa/workspaces/deymos/OWFYI/pokemonbattle_e2e_tests_playwright
    branch: develop
    strategy: depend


final_job:
  stage: final
  image: alpine:latest

  script:
    - echo "Пайплайн завершён"

  when: manual